CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "competition" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "competition_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"duration_months" integer NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"starting_capital" integer NOT NULL,
	"status" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "competition_stock" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "competition_stock_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"competition_id" integer NOT NULL,
	"symbol" text NOT NULL,
	"redacted_symbol" text,
	"redacted_company_name" text,
	"redacted_date" date
);
--> statement-breakpoint
CREATE TABLE "nifty_company" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nifty_company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"symbol" text NOT NULL,
	"company_name" text NOT NULL,
	"stock_file_stem" text NOT NULL,
	"yahoo_symbol" text NOT NULL,
	"status" text NOT NULL,
	"stock_rows" integer NOT NULL,
	"financial_files_written" integer NOT NULL,
	"empty_statements" integer,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "nifty_company_symbol_unique" UNIQUE("symbol"),
	CONSTRAINT "nifty_company_yahoo_symbol_unique" UNIQUE("yahoo_symbol")
);
--> statement-breakpoint
CREATE TABLE "nifty_financial_metric" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nifty_financial_metric_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"symbol" text NOT NULL,
	"statement_type" text NOT NULL,
	"fiscal_year" integer NOT NULL,
	"metric" text NOT NULL,
	"numeric_value" double precision,
	"raw_value" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nifty_stock_daily" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nifty_stock_daily_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"symbol" text NOT NULL,
	"yahoo_symbol" text NOT NULL,
	"trade_date" date NOT NULL,
	"open" double precision,
	"high" double precision,
	"low" double precision,
	"close" double precision,
	"adj_close" double precision,
	"volume" bigint,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "competition_stock" ADD CONSTRAINT "competition_stock_competition_id_competition_id_fk" FOREIGN KEY ("competition_id") REFERENCES "public"."competition"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "competition_stock" ADD CONSTRAINT "competition_stock_symbol_nifty_company_symbol_fk" FOREIGN KEY ("symbol") REFERENCES "public"."nifty_company"("symbol") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "competition_stock_competition_symbol_uq" ON "competition_stock" USING btree ("competition_id","symbol");--> statement-breakpoint
CREATE INDEX "nifty_financial_metric_symbol_idx" ON "nifty_financial_metric" USING btree ("symbol");--> statement-breakpoint
CREATE INDEX "nifty_financial_metric_statement_year_idx" ON "nifty_financial_metric" USING btree ("statement_type","fiscal_year");--> statement-breakpoint
CREATE UNIQUE INDEX "nifty_financial_metric_row_uq" ON "nifty_financial_metric" USING btree ("symbol","statement_type","fiscal_year","metric");--> statement-breakpoint
CREATE INDEX "nifty_stock_daily_symbol_idx" ON "nifty_stock_daily" USING btree ("symbol");--> statement-breakpoint
CREATE INDEX "nifty_stock_daily_trade_date_idx" ON "nifty_stock_daily" USING btree ("trade_date");--> statement-breakpoint
CREATE UNIQUE INDEX "nifty_stock_daily_symbol_trade_date_uq" ON "nifty_stock_daily" USING btree ("symbol","trade_date");