CREATE TABLE "competition_news" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "competition_news_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"competition_id" integer NOT NULL,
	"symbol" text NOT NULL,
	"category" text NOT NULL,
	"rank" integer NOT NULL,
	"title" text NOT NULL,
	"link" text NOT NULL,
	"published_at" timestamp with time zone,
	"source" text,
	"window_from" date NOT NULL,
	"window_to" date NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "competition_news" ADD CONSTRAINT "competition_news_competition_id_competition_id_fk" FOREIGN KEY ("competition_id") REFERENCES "public"."competition"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "competition_news" ADD CONSTRAINT "competition_news_symbol_nifty_company_symbol_fk" FOREIGN KEY ("symbol") REFERENCES "public"."nifty_company"("symbol") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "competition_news_competition_idx" ON "competition_news" USING btree ("competition_id");--> statement-breakpoint
CREATE INDEX "competition_news_symbol_idx" ON "competition_news" USING btree ("symbol");--> statement-breakpoint
CREATE INDEX "competition_news_category_idx" ON "competition_news" USING btree ("category");--> statement-breakpoint
CREATE UNIQUE INDEX "competition_news_comp_symbol_category_rank_uq" ON "competition_news" USING btree ("competition_id","symbol","category","rank");--> statement-breakpoint
CREATE UNIQUE INDEX "competition_news_comp_symbol_category_link_uq" ON "competition_news" USING btree ("competition_id","symbol","category","link");