CREATE TABLE "competition_result" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "competition_result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"competition_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"final_portfolio_value" double precision NOT NULL,
	"profit_loss" double precision NOT NULL,
	"return_pct" double precision NOT NULL,
	"rank" integer DEFAULT 1 NOT NULL,
	"participants_count" integer DEFAULT 1 NOT NULL,
	"rating_before" integer DEFAULT 1000 NOT NULL,
	"rating_delta" integer DEFAULT 0 NOT NULL,
	"rating_after" integer DEFAULT 1000 NOT NULL,
	"completed_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "leaderboard" (
	"user_id" text PRIMARY KEY NOT NULL,
	"rating" integer DEFAULT 1000 NOT NULL,
	"competitions_played" integer DEFAULT 0 NOT NULL,
	"wins" integer DEFAULT 0 NOT NULL,
	"average_return_pct" double precision DEFAULT 0 NOT NULL,
	"best_return_pct" double precision,
	"last_rating_delta" integer DEFAULT 0 NOT NULL,
	"last_played_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "competition_result" ADD CONSTRAINT "competition_result_competition_id_competition_id_fk" FOREIGN KEY ("competition_id") REFERENCES "public"."competition"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "competition_result" ADD CONSTRAINT "competition_result_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "leaderboard" ADD CONSTRAINT "leaderboard_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "competition_result_competition_user_uq" ON "competition_result" USING btree ("competition_id","user_id");--> statement-breakpoint
CREATE INDEX "competition_result_competition_idx" ON "competition_result" USING btree ("competition_id");--> statement-breakpoint
CREATE INDEX "competition_result_user_idx" ON "competition_result" USING btree ("user_id");