CREATE TABLE "volatile_day_summary" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "volatile_day_summary_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"symbol" text NOT NULL,
	"trade_date" date NOT NULL,
	"volatility_pct" double precision NOT NULL,
	"open" double precision NOT NULL,
	"high" double precision NOT NULL,
	"low" double precision NOT NULL,
	"close" double precision NOT NULL,
	"total_volume" bigint NOT NULL,
	"drastic_change_time" timestamp with time zone NOT NULL,
	"drastic_change_pct" double precision NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "volatile_minute_candle" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "volatile_minute_candle_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"symbol" text NOT NULL,
	"trade_date" date NOT NULL,
	"candle_time" timestamp with time zone NOT NULL,
	"open" double precision NOT NULL,
	"high" double precision NOT NULL,
	"low" double precision NOT NULL,
	"close" double precision NOT NULL,
	"volume" bigint NOT NULL,
	"minute_change_pct" double precision,
	"is_drastic_moment" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "volatile_day_summary" ADD CONSTRAINT "volatile_day_summary_symbol_nifty_company_symbol_fk" FOREIGN KEY ("symbol") REFERENCES "public"."nifty_company"("symbol") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "volatile_minute_candle" ADD CONSTRAINT "volatile_minute_candle_symbol_nifty_company_symbol_fk" FOREIGN KEY ("symbol") REFERENCES "public"."nifty_company"("symbol") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "volatile_day_summary_symbol_trade_date_uq" ON "volatile_day_summary" USING btree ("symbol","trade_date");--> statement-breakpoint
CREATE INDEX "volatile_day_summary_trade_date_idx" ON "volatile_day_summary" USING btree ("trade_date");--> statement-breakpoint
CREATE INDEX "volatile_day_summary_symbol_idx" ON "volatile_day_summary" USING btree ("symbol");--> statement-breakpoint
CREATE INDEX "volatile_day_summary_volatility_idx" ON "volatile_day_summary" USING btree ("volatility_pct");--> statement-breakpoint
CREATE UNIQUE INDEX "volatile_minute_candle_symbol_date_time_uq" ON "volatile_minute_candle" USING btree ("symbol","trade_date","candle_time");--> statement-breakpoint
CREATE INDEX "volatile_minute_candle_trade_date_idx" ON "volatile_minute_candle" USING btree ("trade_date");--> statement-breakpoint
CREATE INDEX "volatile_minute_candle_symbol_idx" ON "volatile_minute_candle" USING btree ("symbol");--> statement-breakpoint
CREATE INDEX "volatile_minute_candle_drastic_idx" ON "volatile_minute_candle" USING btree ("is_drastic_moment");